### ISSUE TITLE
Unable to join Community by logging in with Github oAuth

### ISSUE THREAD

**Issue by geckoseo** [WordOps/docs.wordops.net#4]
I'd like to get involved, but when I tried to join the community forum by signing in with Github there appeared to be some kind of strange redirect loop.

It eventually timed out with an error message that I had triggered an anti-spam protection countermeasure, and now if I try I am told there were too many redirections.

I can clear my cookies, but since I've never attempted to register before I don't think the issue is cookie related, it seems like a misconfiguration of the oAuth mechanism?

**Comment by VirtuBox** [comment]
Hello @geckoseo,
issue was related to the domain configured in Github OAuth. It's fixed.
